server {
    listen 80;
    server_name sree84s.site www.sree84s.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name sree84s.site www.sree84s.site;

    ssl_certificate /etc/letsencrypt/live/sree84s.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sree84s.site/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /api {
        proxy_pass http://backend:5000;
    }
}
